---
scenario:
  name: shared
driver:
  name: docker
platforms:
  - name: ansible-role-zsh-debian-12
    image: geerlingguy/docker-debian12-ansible
    pre_build_image: true

  - name: ansible-role-zsh-ubuntu-2204
    image: geerlingguy/docker-ubuntu2204-ansible
    pre_build_image: true

  - name: ansible-role-zsh-ubuntu-2404
    image: geerlingguy/docker-ubuntu2404-ansible
    pre_build_image: true

  - name: ansible-role-zsh-rockylinux-9
    image: geerlingguy/docker-rockylinux9-ansible
    pre_build_image: true

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../..
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/converge.yml
  inventory:
    group_vars:
      all:
        zsh_shared: yes
